### ISSUE TITLE
How send file with node-slumber?

### ISSUE THREAD

**Issue by misteral** [moul/node-slumber#13]
Hello, how I can send file via POST with slumber?

**Comment by moul** [comment]
Hi @misteral 

I just added a new method `.postForm(formData, callback)`

Here is an example ([coffee](https://github.com/moul/node-slumber/blob/master/examples/post-file.coffee), [js](https://github.com/moul/node-slumber/blob/master/examples/post-file.js))

Can you try out on your server and tell me if its working ?

The testing on httpbin.org is limited (see https://github.com/Runscope/httpbin/issues/201), but it seems to be ok when I send all the data to a netcat server

**Comment by misteral** [comment]
@moul hi, I am try it and will send the feedback to you asap. Thanks!

**Comment by misteral** [comment]
@moul thank you.
