### ISSUE TITLE
Appended /? on api calls

### ISSUE THREAD

**Issue by kevinkhill** [moul/node-slumber#5]
Sorry to bother you again, but I think I found another bug...

I created my slumber api as such:
```
this.api = slumber.API(
    'https://api.github.com/', {
    headers : {
      'Accept'        : 'application/vnd.github.v3+json',
      'User-Agent'    : 'Test App',
      'Authorization' : 'token '+this.config.github.personal_access_token
    }
  });
```

And when I do any get request, like ```this.api('user').get()```, I always get a 404 error.

I thought maybe it was me, so I tested the request with curl and my headers. When I query ```https://api.github.com/user``` I get the proper response, so after some digging into the ```fullRequestResponse``` I found that a ```/?``` is getting appended to my query producing ```https://api.github.com/user/?``` which in turn Github replies with a 404

I'll try and help with a pull request, but I am not very proficient with coffeescript, sorry!

**Comment by moul** [comment]
Fixed with #6, thanks :+1:
