### ISSUE TITLE
Typo fix

### ISSUE THREAD

**Issue by budnix** [moul/node-slumber#9]
Hi, Can I ask for release new version with fixed this typo in delete method (https://github.com/moul/node-slumber/blob/v0.7.0/lib/API.js#L242)? This typo is not exists into master but still exists in 0.7.0 which is the latest version registered in npm.

Thanks!

**Comment by moul** [comment]
Yes sure, it's in progress

**Comment by budnix** [comment]
Thanks! :beer:

**Comment by moul** [comment]
version 0.8.0 released with the fix
